### ISSUE TITLE
docker compose error on a raspberry pi 3

### ISSUE THREAD

**Issue by cybergogo** [anyone-protocol/anon-install#1]
Hello Team,
I'm trying to use your relay on a Rpi 3 B+ but am encountering this error when entering this command:
sudo docker compose -f /opt/compose-files/relay.yaml up -d

Here is the error: 
WARN[0000] /opt/compose-files/relay.yaml: `version` is obsolete
[+] Running 0/1
 ⠴ relay Pulling                                                           1.5s
no matching manifest for linux/arm/v7 in the manifest list entries

I was under the impression that the docker image was arm64 compatible and wasn't expecting this message (also i'm not a dev but more of a tech enthousiast very determined when testing new stuff).

I hope you'll be able to tell me if there is a way around it or if the compatibility is just not there at the moment.
Wish you the best for this project.

Charlie

**Comment by rA3ka** [comment]
Ensure that you have a 64-bits operating system installed

**Comment by cybergogo** [comment]
> Ensure that you have a 64-bits operating system installed

Thank you, i've tested with a rpi 5 and it worked flawlessly. I think pi imager forced the 32bit image on the SD for the rpi 3. I'll check and try 64-bits on it 👍

Just need to have a dashboard to watch the rewards coming in 🙏

**Comment by rA3ka** [comment]
Great. Join our discord and/or telegram community found on our website for more information and discussions regarding all this. I will close this issue.
