### ISSUE TITLE
ExecStart=/bin/true ?

### ISSUE THREAD

**Issue by markjr** [anyone-protocol/anon-install#2]
Is it because this is still in testing that ExecStart=/bin/true and not /usr/sbin/anon?

**Comment by cl0ten** [comment]
Hello,

we covered this in the discord support server but for clarification, posting the relevant comments here.

cl0ten:
_from what I can read; it's for hardening purposes as it will read the anonrc-defaults file unless changed from bin/true.
changing to /usr/sbin/anon would make it run as root and you'd also have to specify "-f /etc/anon/anonrc" to load the configuration_

mjeftovic:
_Yes that seems to work - also need to change Type=simple
although no matter what I do, --RunAsDaemon is always 0
but it's running_

Source:
https://discord.com/channels/1083735132470521907/1115662387811467427/1226575028980809789

Have a great day!
